from __future__ import annotations

from app.v2.knowledge_base.step_01_models import ApplicationState


APP_OWNED_APPLICATION_STATES: tuple[ApplicationState, ...] = (
    ApplicationState(
        sheet_row=1,
        state="created",
        terminal=False,
        allowed_next_states=("uploading", "analyzing", "failed"),
        entered_when_de="Session und Post-Typ wurden angelegt.",
        required_data=("session_id", "post_type_key"),
        ui_behavior_de="Upload- und Texteingabe anzeigen.",
    ),
    ApplicationState(
        sheet_row=2,
        state="uploading",
        terminal=False,
        allowed_next_states=("analyzing", "failed"),
        entered_when_de="Fotos, Audio oder manueller Text werden gespeichert.",
        required_data=("session_id",),
        ui_behavior_de="Uploadfortschritt anzeigen.",
    ),
    ApplicationState(
        sheet_row=3,
        state="analyzing",
        terminal=False,
        allowed_next_states=("needs_input", "ready_to_generate", "failed"),
        entered_when_de="Transkription, Fakten- oder Bildanalyse lauft.",
        required_data=("stored_audio_refs OR manual_text", "stored_image_refs optional"),
        ui_behavior_de="Analysefortschritt anzeigen.",
    ),
    ApplicationState(
        sheet_row=4,
        state="needs_input",
        terminal=False,
        allowed_next_states=("analyzing", "ready_to_generate", "failed"),
        entered_when_de="Pflichtfakten fehlen oder Angaben widersprechen sich.",
        required_data=("clarification_questions",),
        ui_behavior_de="Gebundelte Ruckfragen anzeigen.",
    ),
    ApplicationState(
        sheet_row=5,
        state="ready_to_generate",
        terminal=False,
        allowed_next_states=("generating", "failed"),
        entered_when_de="Kritische Fakten wurden bestatigt.",
        required_data=("confirmed_post_facts_json",),
        ui_behavior_de="Generierung starten.",
    ),
    ApplicationState(
        sheet_row=6,
        state="generating",
        terminal=False,
        allowed_next_states=("needs_review", "needs_input", "failed"),
        entered_when_de="Content, Links oder Bilder werden verarbeitet.",
        required_data=("generation_context",),
        ui_behavior_de="Fortschritt nach Workflow-Schritt anzeigen.",
    ),
    ApplicationState(
        sheet_row=7,
        state="needs_review",
        terminal=False,
        allowed_next_states=("ready_to_publish", "generating", "failed"),
        entered_when_de="Validierter Entwurf wartet auf Prufung.",
        required_data=("wordpress_payload", "validation_report"),
        ui_behavior_de="Editierbare Vorschau anzeigen.",
    ),
    ApplicationState(
        sheet_row=8,
        state="ready_to_publish",
        terminal=False,
        allowed_next_states=("publishing", "needs_review", "failed"),
        entered_when_de="Nutzer hat den Entwurf freigegeben.",
        required_data=("approved_draft",),
        ui_behavior_de="Publish-Aktion aktivieren.",
    ),
    ApplicationState(
        sheet_row=9,
        state="publishing",
        terminal=False,
        allowed_next_states=("published", "failed"),
        entered_when_de="WordPress-Ubertragung lauft.",
        required_data=("approved_draft", "idempotency_key"),
        ui_behavior_de="Doppeltes Absenden verhindern.",
    ),
    ApplicationState(
        sheet_row=10,
        state="published",
        terminal=True,
        allowed_next_states=(),
        entered_when_de="WordPress-Beitrag wurde erstellt.",
        required_data=("post_id", "view_url", "edit_url"),
        ui_behavior_de="Ergebnislinks anzeigen.",
    ),
    ApplicationState(
        sheet_row=11,
        state="failed",
        terminal=False,
        allowed_next_states=("uploading", "analyzing", "generating", "publishing"),
        entered_when_de="Ein Workflow-Schritt ist fehlgeschlagen.",
        required_data=("error_code", "failed_step"),
        ui_behavior_de="Gezielten Retry anbieten.",
    ),
)