from __future__ import annotations

from app.v2.knowledge_base.step_01_models import WorkflowStep


APP_OWNED_WORKFLOW_STEPS: tuple[WorkflowStep, ...] = (
    WorkflowStep(
        sheet_row=1,
        step_order=10,
        step_key="create_session",
        owner="application",
        input="authenticated_user + post_type_key",
        action_de="Post-Typ gegen post_types prufen und Session anlegen.",
        output="session_record",
        required=True,
        run_condition="always",
        failure_action_de="Unbekannten, deaktivierten oder nicht bereiten Post-Typ ablehnen.",
    ),
    WorkflowStep(
        sheet_row=2,
        step_order=20,
        step_key="upload_photos",
        owner="application",
        input="image_files[]",
        action_de="Fotos validieren und Originale dauerhaft speichern.",
        output="stored_image_refs",
        required=False,
        run_condition="image_count_gt_0",
        failure_action_de="Ungultige Bilder ablehnen; gultige Uploads behalten.",
    ),
    WorkflowStep(
        sheet_row=3,
        step_order=30,
        step_key="upload_voice_messages",
        owner="application",
        input="audio_files[] or manual_text",
        action_de="Sprachnachrichten oder manuellen Text speichern.",
        output="stored_input_refs",
        required=True,
        run_condition="always",
        failure_action_de="Mindestens eine Sprachnachricht oder manuellen Text verlangen.",
    ),
    WorkflowStep(
        sheet_row=4,
        step_order=40,
        step_key="transcribe_voice",
        owner="speech_to_text",
        input="stored_audio_refs when present",
        action_de="Nur vorhandene Sprachnachrichten transkribieren; bei reinem manual_text erfolgreich uberspringen.",
        output="voice_transcript",
        required=False,
        run_condition="audio_count_gt_0",
        failure_action_de="Bei Audiofehler manuellen Text erlauben oder Aufnahme erneut senden lassen.",
    ),
    WorkflowStep(
        sheet_row=5,
        step_order=50,
        step_key="extract_facts",
        owner="language_model",
        input="transcript + manual_text + ACF_fields_schema input_fact rows",
        action_de="Nur bestatigbare Fakten nach dem ausgewahlten Post-Typ extrahieren.",
        output="post_facts_json",
        required=True,
        run_condition="always",
        failure_action_de="Fehlende Werte markieren; niemals erfinden.",
    ),
    WorkflowStep(
        sheet_row=6,
        step_order=60,
        step_key="analyze_photos",
        owner="vision_model",
        input="stored_image_refs + image_analysis_rules",
        action_de="Bildinhalt, Qualitat, Rolle und Featured-Eignung strukturiert analysieren.",
        output="image_analysis_json",
        required=False,
        run_condition="image_count_gt_0",
        failure_action_de="Ohne Vision mit technischer Pillow-Prufung und manueller Reihenfolge fortfahren.",
    ),
    WorkflowStep(
        sheet_row=7,
        step_order=70,
        step_key="clarify_missing",
        owner="language_model",
        input="post_facts_json + ACF_fields_schema.required_for_analysis + required output source facts",
        action_de="Fehlende Pflichtfakten und Widerspruche bundeln. Ruckfragen stellen, bevor abhangige Pflichtfelder generiert werden.",
        output="clarification_questions",
        required=True,
        run_condition="always",
        failure_action_de="Generierung blockieren, solange fur Pflichtfelder notwendige bestatigte Fakten fehlen.",
    ),
    WorkflowStep(
        sheet_row=8,
        step_order=80,
        step_key="save_user_corrections",
        owner="application",
        input="user_answers + version",
        action_de="Antworten versioniert speichern und Fakten bestatigen.",
        output="confirmed_post_facts_json",
        required=True,
        run_condition="always",
        failure_action_de="Validierungsfehler feldbezogen anzeigen.",
    ),
    WorkflowStep(
        sheet_row=9,
        step_order=90,
        step_key="build_context",
        owner="application",
        input="post_type_key + confirmed facts + context_building",
        action_de="Nur relevante Regeln, Felder, Beispiele und Links laden.",
        output="generation_context",
        required=True,
        run_condition="always",
        failure_action_de="Bei ungultiger Knowledge-Konfiguration laut fehlschlagen.",
    ),
    WorkflowStep(
        sheet_row=10,
        step_order=100,
        step_key="generate_shared_fields",
        owner="language_model",
        input="generation_context + shared_fields_schema",
        action_de="WordPress- und Yoast-Felder als strukturiertes JSON erzeugen.",
        output="shared_draft_json",
        required=True,
        run_condition="always",
        failure_action_de="Gezielt anhand der Validierungsfehler erneut generieren.",
    ),
    WorkflowStep(
        sheet_row=11,
        step_order=110,
        step_key="generate_acf_fields",
        owner="language_model",
        input="generation_context + ACF_fields_schema",
        action_de="Direkte ACF-Felder und Aggregationsquellen erzeugen.",
        output="acf_source_json",
        required=True,
        run_condition="always",
        failure_action_de="Unbekannte Feldschlussel ablehnen.",
    ),
    WorkflowStep(
        sheet_row=12,
        step_order=120,
        step_key="select_internal_links",
        owner="language_model",
        input="eligible links + internal link context",
        action_de="Geeignete Links semantisch ranken und naturliche Anker vorschlagen.",
        output="selected_links",
        required=False,
        run_condition="always",
        failure_action_de="Ohne Link fortfahren, wenn keine gultige URL passt.",
    ),
    WorkflowStep(
        sheet_row=13,
        step_order=130,
        step_key="build_related_links_html",
        owner="application",
        input="selected_links + internal_link_rules",
        action_de="Links validieren und related_links_html erzeugen.",
        output="related_links_html",
        required=False,
        run_condition="always",
        failure_action_de="Ungultige, doppelte oder selbstreferenzierende Links entfernen.",
    ),
    WorkflowStep(
        sheet_row=14,
        step_order=140,
        step_key="process_images",
        owner="pillow",
        input="stored images + image_rules_pillow + optional analysis",
        action_de="Pillow-Payload ausschlieslich aus image_rules_pillow bauen und Bilder bearbeiten.",
        output="processed_image_refs",
        required=False,
        run_condition="image_count_gt_0",
        failure_action_de="Originale behalten und betroffenes Bild zur Prufung markieren.",
    ),
    WorkflowStep(
        sheet_row=15,
        step_order=150,
        step_key="generate_image_metadata",
        owner="language_model",
        input="image analysis + image_metadata_schema + SEO context",
        action_de="Metadaten fur jedes verwendete Bild erzeugen.",
        output="image_metadata_json",
        required=False,
        run_condition="image_count_gt_0",
        failure_action_de="Wenn Bilder vorhanden sind, Fehler feldbezogen anzeigen; ohne Bilder den Schritt erfolgreich uberspringen.",
    ),
    WorkflowStep(
        sheet_row=16,
        step_order=160,
        step_key="build_payload",
        owner="application",
        input="shared draft + ACF sources + related_links_html",
        action_de="WordPress-, Yoast- und ACF-Payload deterministisch zusammensetzen.",
        output="wordpress_payload",
        required=True,
        run_condition="always",
        failure_action_de="Bei unbekanntem Ziel oder Transformationsschlussel abbrechen.",
    ),
    WorkflowStep(
        sheet_row=17,
        step_order=170,
        step_key="validate_draft",
        owner="application",
        input="wordpress_payload + active validators",
        action_de="Pflichtfelder, Typen, Langen, HTML, Links und Medien prufen.",
        output="validation_report",
        required=True,
        run_condition="always",
        failure_action_de="Fehler in der App anzeigen und betroffenen Schritt erneut ausfuhren.",
    ),
    WorkflowStep(
        sheet_row=18,
        step_order=180,
        step_key="review_draft",
        owner="user",
        input="validated draft",
        action_de="Vollstandigen Entwurf in der App prufen und freigeben.",
        output="approved_draft",
        required=True,
        run_condition="always",
        failure_action_de="Ohne ausdruckliche Freigabe nicht an WordPress senden.",
    ),
    WorkflowStep(
        sheet_row=19,
        step_order=190,
        step_key="publish_wordpress",
        owner="wordpress_api",
        input="approved_draft + idempotency_key",
        action_de="Beitrag und Medien als draft oder private erstellen.",
        output="post_result",
        required=True,
        run_condition="always",
        failure_action_de="Fehler speichern; Publishing idempotent wiederholen.",
    ),
)