from __future__ import annotations

from backend.app.knowledge_base.step_01_models import ContextManifestRow


APP_OWNED_CONTEXT_MANIFEST: tuple[ContextManifestRow, ...] = (
    ContextManifestRow(
        sheet_row=1,
        context_stage="fact_extraction",
        source_sheet="ACF_fields_schema",
        filter_expression="enabled=TRUE AND post_type_key={post_type_key} AND field_role=input_fact",
        sort_order="field_key",
        max_items=None,
        output_key="fact_schema",
        owner="application",
        required=True,
        purpose_de="Definiert ausschlieslich die Fakten, die aus Nutzereingaben extrahiert und gepruft werden.",
    ),
    ContextManifestRow(
        sheet_row=2,
        context_stage="shared_generation",
        source_sheet="shared_fields_schema",
        filter_expression="enabled=TRUE AND include_in_ai_schema=TRUE AND generation_stage IN (content_generation,seo_generation)",
        sort_order="group,field_key",
        max_items=None,
        output_key="shared_field_schema",
        owner="application",
        required=True,
        purpose_de="Definiert WordPress- und Yoast-Felder, die das Modell erzeugen darf.",
    ),
    ContextManifestRow(
        sheet_row=3,
        context_stage="acf_generation",
        source_sheet="ACF_fields_schema",
        filter_expression="enabled=TRUE AND post_type_key={post_type_key} AND include_in_ai_schema=TRUE AND field_role!=input_fact",
        sort_order="section,aggregation_order,field_key",
        max_items=None,
        output_key="acf_generation_schema",
        owner="application",
        required=True,
        purpose_de="Definiert direkte ACF-Felder und Aggregationsquellen.",
    ),
    ContextManifestRow(
        sheet_row=4,
        context_stage="global_instructions",
        source_sheet="agent_instructions",
        filter_expression="enabled=TRUE AND owner=language_model AND (post_type_key=* OR post_type_key={post_type_key})",
        sort_order="priority DESC,instruction_id",
        max_items=None,
        output_key="agent_instructions",
        owner="application",
        required=True,
        purpose_de="Ladt nur stabile AI-Verhaltensregeln.",
    ),
    ContextManifestRow(
        sheet_row=5,
        context_stage="seo_context",
        source_sheet="seo_rules",
        filter_expression="enabled=TRUE AND (post_type_key=* OR post_type_key={post_type_key}) AND stage={stage} AND target matches requested field/group",
        sort_order="priority DESC,rule_id",
        max_items=None,
        output_key="seo_rules",
        owner="application",
        required=False,
        purpose_de="Ladt SEO-Regeln gezielt pro Feld, Gruppe oder Validierungsstufe.",
    ),
    ContextManifestRow(
        sheet_row=6,
        context_stage="style_context",
        source_sheet="style_rules",
        filter_expression="enabled=TRUE AND (post_type_key=* OR post_type_key={post_type_key}) AND match(global OR current section OR detected tags)",
        sort_order="priority DESC,rule_id",
        max_items=None,
        output_key="style_rules",
        owner="application",
        required=False,
        purpose_de="Ladt globale und kontextuell passende Stilregeln.",
    ),
    ContextManifestRow(
        sheet_row=7,
        context_stage="story_context",
        source_sheet="story_patterns",
        filter_expression="enabled=TRUE AND post_type_key={post_type_key} AND trigger_tags intersects {context_tags} AND required_facts available",
        sort_order="priority DESC,pattern_id",
        max_items=2,
        output_key="story_patterns",
        owner="application",
        required=False,
        purpose_de="Wahlt hochstens ein primares Muster plus optional challenge_solution.",
    ),
    ContextManifestRow(
        sheet_row=8,
        context_stage="blueprint",
        source_sheet="post_blueprint",
        filter_expression="enabled=TRUE AND post_type_key={post_type_key}",
        sort_order="section_order",
        max_items=None,
        output_key="post_blueprint",
        owner="application",
        required=True,
        purpose_de="Ladt Aufbau, Reihenfolge, Zweck und explizite Zielrelationen des ausgewahlten Post-Typs.",
    ),
    ContextManifestRow(
        sheet_row=9,
        context_stage="examples",
        source_sheet="post_examples",
        filter_expression="enabled=TRUE AND approved=TRUE AND post_type_key={post_type_key}",
        sort_order="quality_score DESC",
        max_items=5,
        output_key="examples",
        owner="application",
        required=False,
        purpose_de="Ladt nur relevante, freigegebene Beispiele; keine anderen Post-Typen.",
    ),
    ContextManifestRow(
        sheet_row=10,
        context_stage="internal_links",
        source_sheet="internal_links_database",
        filter_expression="active=TRUE AND target_url!=TBD AND (post_type_key=* OR post_type_key={post_type_key}) AND canonical_path(target_url)!={current_path}",
        sort_order="priority DESC,link_id",
        max_items=12,
        output_key="eligible_links",
        owner="application",
        required=False,
        purpose_de="Python filtert harte Kriterien und leitet den kanonischen Pfad aus target_url ab; AI rankt usage_context semantisch. Select eligible candidates and produce field-level placement instructions for existing ACF text.",
    ),
    ContextManifestRow(
        sheet_row=11,
        context_stage="image_analysis",
        source_sheet="image_analysis_rules",
        filter_expression="enabled=TRUE",
        sort_order="priority DESC,rule_id",
        max_items=None,
        output_key="image_analysis_schema",
        owner="application",
        required=False,
        purpose_de="Definiert ausschlieslich Analyseausgaben, keine Bildbearbeitungsparameter.",
    ),
    ContextManifestRow(
        sheet_row=12,
        context_stage="image_processing",
        source_sheet="image_rules_pillow",
        filter_expression="enabled=TRUE AND condition satisfied",
        sort_order="priority DESC,rule_key",
        max_items=None,
        output_key="pillow_payload",
        owner="application",
        required=False,
        purpose_de="Einzige Quelle aller Pillow-Parameterwerte.",
    ),
    ContextManifestRow(
        sheet_row=13,
        context_stage="image_metadata",
        source_sheet="image_metadata_schema",
        filter_expression="enabled=TRUE",
        sort_order="field_key",
        max_items=None,
        output_key="image_metadata_schema",
        owner="application",
        required=False,
        purpose_de="Definiert alle erzeugten WordPress-Mediendaten.",
    ),
)