from __future__ import annotations

from backend.app.knowledge_base.step_01_models import ImageAnalysisRule


APP_OWNED_IMAGE_ANALYSIS_RULES: tuple[ImageAnalysisRule, ...] = (
    ImageAnalysisRule(
        sheet_row=1,
        rule_id="img_an_001",
        enabled=True,
        analysis_key="main_subject",
        intent_de="Hauptmotiv und sichtbare Kernelemente beschreiben",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="short_text",
        output_domain=None,
        used_by="image metadata; featured selection",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=2,
        rule_id="img_an_002",
        enabled=True,
        analysis_key="featured_score",
        intent_de="Eignung als Featured Image von 0 bis 100 bewerten",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="integer_0_100",
        output_domain=None,
        used_by="featured selection",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=3,
        rule_id="img_an_003",
        enabled=True,
        analysis_key="gallery_role",
        intent_de="Rolle bestimmen: overview, action, cocktail, bartender, guests, branding, detail",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="enum",
        output_domain="gallery_role",
        used_by="gallery ordering",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=4,
        rule_id="img_an_004",
        enabled=True,
        analysis_key="composition_score",
        intent_de="Komposition und Motivklarheit bewerten",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="integer_0_100",
        output_domain=None,
        used_by="featured selection; review",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=5,
        rule_id="img_an_005",
        enabled=True,
        analysis_key="crop_recommendation",
        intent_de="Empfohlenen Fokuspunkt und sicheren Beschnitt beschreiben",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="normalized_focal_point_or_none",
        output_domain=None,
        used_by="Pillow crop payload",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=6,
        rule_id="img_an_006",
        enabled=True,
        analysis_key="horizon_tilt_degrees",
        intent_de="Schiefe Horizonte oder Barlinien erkennen",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="float_or_zero",
        output_domain=None,
        used_by="manual review; optional local correction",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=7,
        rule_id="img_an_007",
        enabled=True,
        analysis_key="brightness_score",
        intent_de="Bildhelligkeit von 0 bis 100 bewerten",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="integer_0_100",
        output_domain=None,
        used_by="Pillow condition image_dark",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=8,
        rule_id="img_an_008",
        enabled=True,
        analysis_key="contrast_score",
        intent_de="Kontrast von 0 bis 100 bewerten",
        owner="vision_model",
        condition="always",
        priority="low",
        expected_output="integer_0_100",
        output_domain=None,
        used_by="Pillow diagnostics",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=9,
        rule_id="img_an_009",
        enabled=True,
        analysis_key="noise_score",
        intent_de="Sichtbares Bildrauschen von 0 bis 100 bewerten",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="integer_0_100",
        output_domain=None,
        used_by="Pillow condition noise_score_gt_20",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=10,
        rule_id="img_an_010",
        enabled=True,
        analysis_key="highlight_clipping_risk",
        intent_de="Risiko ausgebrannter heller Bereiche bewerten",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="low|medium|high",
        output_domain="risk_level",
        used_by="review",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=11,
        rule_id="img_an_011",
        enabled=True,
        analysis_key="skin_tone_risk",
        intent_de="Unnaturliche Hauttone erkennen, ohne Personen zu identifizieren",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="low|medium|high",
        output_domain="risk_level",
        used_by="review",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=12,
        rule_id="img_an_012",
        enabled=True,
        analysis_key="cocktail_prominence",
        intent_de="Sichtbarkeit von Cocktails, Garnitur und Bar bewerten",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="integer_0_100",
        output_domain=None,
        used_by="featured selection; metadata",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=13,
        rule_id="img_an_013",
        enabled=True,
        analysis_key="background_distraction",
        intent_de="Storende Hintergrunde oder Objekte beschreiben",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="short_text_or_none",
        output_domain=None,
        used_by="image API decision; review",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=14,
        rule_id="img_an_014",
        enabled=True,
        analysis_key="duplicate_group",
        intent_de="Nahezu identische Bilder gruppieren",
        owner="vision_model",
        condition="always",
        priority="medium",
        expected_output="group_id_or_none",
        output_domain=None,
        used_by="gallery deduplication",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=15,
        rule_id="img_an_015",
        enabled=True,
        analysis_key="needs_image_api",
        intent_de="Nur komplexe, nicht mit Pillow losbare Anderungen markieren",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="boolean_with_reason",
        output_domain=None,
        used_by="image API routing",
        fallback="manual_review",
    ),
    ImageAnalysisRule(
        sheet_row=16,
        rule_id="img_an_016",
        enabled=True,
        analysis_key="visible_roles",
        intent_de="Sichtbare Rollen als kontrollierte Liste erkennen, ohne Personen zu identifizieren.",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="enum_list",
        output_domain="image_visible_role",
        used_by="image metadata rules",
        fallback="empty_list",
    ),
    ImageAnalysisRule(
        sheet_row=17,
        rule_id="img_an_017",
        enabled=True,
        analysis_key="visible_actions",
        intent_de="Sichtbare Handlungen als kontrollierte Liste erkennen.",
        owner="vision_model",
        condition="always",
        priority="high",
        expected_output="enum_list",
        output_domain="image_visible_action",
        used_by="image metadata rules",
        fallback="empty_list",
    ),
)