from __future__ import annotations

from backend.app.knowledge_base.step_01_models import InternalLinkRule


APP_OWNED_INTERNAL_LINK_RULES: tuple[InternalLinkRule, ...] = (
    InternalLinkRule(
        sheet_row=1,
        rule_id="rule_01",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="between",
        value="2;4",
        value_type="list",
        instruction_de="Pro Eventpost 2-4 passende interne Links vorschlagen oder einbauen",
        priority="high",
    ),
    InternalLinkRule(
        sheet_row=2,
        rule_id="rule_02",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Keine Selbstverlinkung auf die aktuell erzeugte Zielseite",
        priority="high",
    ),
    InternalLinkRule(
        sheet_row=3,
        rule_id="rule_03",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Nur Links verwenden, bei denen active=yes steht",
        priority="high",
    ),
    InternalLinkRule(
        sheet_row=4,
        rule_id="rule_04",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Links mit priority=high bevorzugen",
        priority="high",
    ),
    InternalLinkRule(
        sheet_row=5,
        rule_id="rule_05",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="max",
        value=1,
        value_type="integer",
        instruction_de="Maximal 1 interner Link pro Absatz",
        priority="medium",
    ),
    InternalLinkRule(
        sheet_row=6,
        rule_id="rule_06",
        enabled=True,
        owner="language_model",
        action_type="instruction",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Anchor-Texte naturlich in den Satz einbauen, nicht keyword-stuffing",
        priority="high",
    ),
    InternalLinkRule(
        sheet_row=7,
        rule_id="rule_07",
        enabled=True,
        owner="language_model",
        action_type="instruction",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Service-Seiten vor Eventpost-Beispielen bevorzugen",
        priority="medium",
    ),
    InternalLinkRule(
        sheet_row=8,
        rule_id="rule_08",
        enabled=True,
        owner="language_model",
        action_type="instruction",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Eventtyp-Seiten verwenden, wenn der Eventtyp klar passt",
        priority="medium",
    ),
    InternalLinkRule(
        sheet_row=9,
        rule_id="rule_09",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Nicht denselben Anchor mehrfach im selben Post verwenden",
        priority="medium",
    ),
    InternalLinkRule(
        sheet_row=10,
        rule_id="rule_10",
        enabled=True,
        owner="application",
        action_type="constraint",
        applies_to="internal_links",
        operator="instruction",
        value="yes",
        value_type="string",
        instruction_de="Wenn keine passende URL vorhanden ist, keinen Link auswahlen und den Grund protokollieren.",
        priority="high",
    ),
)