from __future__ import annotations

from backend.app.knowledge_base.step_01_models import OutputSpecification


APP_OWNED_OUTPUT_SPECIFICATIONS: tuple[OutputSpecification, ...] = (
    OutputSpecification(
        sheet_row=1,
        setting_key="input_mode",
        enabled=True,
        value="direct_app_upload",
        value_type="enum",
        required=True,
        description_de="Sprachnachrichten und Fotos werden direkt in der App hochgeladen.",
        example="direct_app_upload",
        validation_rule="must_equal:direct_app_upload",
    ),
    OutputSpecification(
        sheet_row=2,
        setting_key="session_required",
        enabled=True,
        value=True,
        value_type="boolean",
        required=True,
        description_de="Jeder Beitrag wird innerhalb einer persistenten Session verarbeitet.",
        example="TRUE",
        validation_rule="boolean",
    ),
    OutputSpecification(
        sheet_row=3,
        setting_key="voice_messages_min",
        enabled=True,
        value=1,
        value_type="integer",
        required=True,
        description_de="Mindestens eine Sprachnachricht oder alternativ ein manuell eingegebener Text.",
        example="1",
        validation_rule="min:1 unless manual_text_present",
    ),
    OutputSpecification(
        sheet_row=4,
        setting_key="photos_min",
        enabled=True,
        value=0,
        value_type="integer",
        required=False,
        description_de="Fotos sind optional.",
        example="0",
        validation_rule="min:0",
    ),
    OutputSpecification(
        sheet_row=5,
        setting_key="photos_max",
        enabled=True,
        value=20,
        value_type="integer",
        required=False,
        description_de="Maximale Anzahl hochgeladener Fotos pro Session.",
        example="20",
        validation_rule="max:20",
    ),
    OutputSpecification(
        sheet_row=6,
        setting_key="default_language",
        enabled=True,
        value="de-DE",
        value_type="string",
        required=True,
        description_de="Standardsprache fur Ruckfragen und Website-Inhalte.",
        example="de-DE",
        validation_rule="BCP47",
    ),
    OutputSpecification(
        sheet_row=7,
        setting_key="draft_output",
        enabled=True,
        value="structured_json",
        value_type="enum",
        required=True,
        description_de="Entwurf wird als strukturiertes JSON in der Session gespeichert.",
        example="structured_json",
        validation_rule="schema:event_post_draft",
    ),
    OutputSpecification(
        sheet_row=8,
        setting_key="wordpress_delivery",
        enabled=True,
        value="direct_api",
        value_type="enum",
        required=True,
        description_de="Beitrag und Medien werden direkt uber die WordPress-API ubertragen.",
        example="direct_api",
        validation_rule="must_equal:direct_api",
    ),
    OutputSpecification(
        sheet_row=9,
        setting_key="default_publish_status",
        enabled=True,
        value="draft",
        value_type="enum",
        required=True,
        description_de="Standardstatus vor finaler Prufung.",
        example="draft",
        validation_rule="enum:draft|private",
    ),
    OutputSpecification(
        sheet_row=10,
        setting_key="image_edit_mode_default",
        enabled=True,
        value="selective",
        value_type="enum",
        required=True,
        description_de="Pillow zuerst; Image API nur fur markierte Problemfalle.",
        example="selective",
        validation_rule="enum:local|selective|ai_all",
    ),
    OutputSpecification(
        sheet_row=11,
        setting_key="return_payload",
        enabled=True,
        value="post_id,view_url,edit_url,status",
        value_type="list",
        required=True,
        description_de="Erfolgsantwort an die App.",
        example="post_id; view_url; edit_url; status",
        validation_rule="all_required",
    ),
    OutputSpecification(
        sheet_row=12,
        setting_key="no_zip_input",
        enabled=True,
        value=True,
        value_type="boolean",
        required=True,
        description_de="ZIP-Dateien werden nicht als Eingabe akzeptiert.",
        example="TRUE",
        validation_rule="boolean",
    ),
    OutputSpecification(
        sheet_row=13,
        setting_key="no_zip_output",
        enabled=True,
        value=True,
        value_type="boolean",
        required=True,
        description_de="Es wird keine ZIP-Datei erzeugt oder zuruckgegeben.",
        example="TRUE",
        validation_rule="boolean",
    ),
)